version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run: 
        - name: Install dependencies
          command: npm install
        - name: 

      - run:
        - name: Run tests
        - command: npm run test

workflows:
  test-run:
    jobs:
      - build