version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  test-1:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Echo 1
          command: echo 1
  test-2:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Echo 2
          command: echo 2
  print-hello:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Print hello
          command: echo hello world
  deploy:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo deploying
  save-hello-world-output:
    docker:
      - image: cimg/node:19.4.0
    working_directory: workspace
    steps:
      - checkout
      - run:
          name: Save to workspace
          command: mkdir -p workspace/echo 
      - run: touch /workspace/echo/output.txt
      - run: echo "Text to be moved" > workspace/echo/output.txt
      - run: ls
      - persist_to_workspace:
          root: /workspace
          paths:
            - echo
  print-output-file:
    docker:
      - image: cimg/node:19.4.0
    working_directory: /workspace
    steps:
      - attach_workspace:
          at: /workspace/echo
      - run:
          name: Output file 
          command: cat /workspace/echo/output.txt

workflows:
  test-run:
    jobs:
      - build
      - test-1:
          requires:
            - build
      - test-2:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test-1
            - test-2
      - deploy:
          requires:
            - hold
      - save-hello-world-output
      - print-output-file:
          requires:
            - save-hello-world-output
