version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  test-1:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Echo 1
          command: echo 1
  test-2:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Echo 2
          command: echo 2
  deploy:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo deploying
  buildLast:
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  test-run:
    jobs:
      - build
      - test-1:
          requires:
            - build
      - test-2:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test-1
            - test-2
      - deploy:
          requires:
            - hold
      - buildLast